# Generated by Django 2.2 on 2020-08-21 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=30)),
                ('año', models.IntegerField()),
                ('status', models.CharField(choices=[('IN', 'Biblioteca'), ('BW', 'Prestado'), ('RQ', 'Pedido'), ('RV', 'Reservado')], default='Biblioteca', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Materiales de Lectura',
                'verbose_name': 'Material de Lectura',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('num_libros', models.IntegerField()),
                ('deuda', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.Persona')),
                ('matricula', models.IntegerField()),
            ],
            bases=('biblioteca.persona',),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.Material')),
                ('editorial', models.CharField(max_length=40)),
                ('fotoPortada', models.ImageField(blank=True, upload_to='portadas/')),
            ],
            bases=('biblioteca.material',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.Persona')),
                ('num_empleado', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Profesores',
                'verbose_name': 'Profesor',
            },
            bases=('biblioteca.persona',),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biblioteca.Material')),
            ],
            bases=('biblioteca.material',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('fecha_salida', models.DateField()),
                ('fecha_regreso', models.DateField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Material')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.Persona')),
            ],
        ),
    ]
